[features]
seeds = false
[programs.localnet]
decentralized_news = "GKQz8VpfXHbj2hXeazQHq1YzN8XvZyQQM2rhpHYJfake"

[programs.devnet]
decentralized_news = "GKQz8VpfXHbj2hXeazQHq1YzN8XvZyQQM2rhpHYJfake"

[programs.mainnet]
decentralized_news = "GKQz8VpfXHbj2hXeazQHq1YzN8XvZyQQM2rhpHYJfake"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/rostik/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
